-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.cases
(
    case_id serial NOT NULL,
    purchase_id integer NOT NULL,
    partner_case_number character varying(100) COLLATE pg_catalog."default",
    due_date date NOT NULL,
    current_due_date date NOT NULL,
    amount numeric(16, 3) NOT NULL,
    current_amount numeric(16, 3) NOT NULL,
    interest_rate numeric(6, 3) NOT NULL,
    current_interest_rate numeric(6, 3) NOT NULL,
    current_interest_amount numeric(16, 3) NOT NULL,
    calculated_purchase_value numeric(16, 3),
    closed_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone,
    deleted_at timestamp with time zone,
    CONSTRAINT case_pkey PRIMARY KEY (case_id)
);

CREATE TABLE IF NOT EXISTS public.cities
(
    city_id serial NOT NULL,
    name character varying(200) COLLATE pg_catalog."default" NOT NULL,
    region_id integer NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone,
    deleted_at timestamp with time zone,
    CONSTRAINT cities_pkey PRIMARY KEY (city_id)
);

CREATE TABLE IF NOT EXISTS public.debtor_types
(
    debtor_type_id serial NOT NULL,
    name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone,
    deleted_at timestamp with time zone,
    CONSTRAINT debtor_type_pkey PRIMARY KEY (debtor_type_id)
);

CREATE TABLE IF NOT EXISTS public.debtors
(
    debtor_id serial NOT NULL,
    case_id integer NOT NULL,
    person_id integer NOT NULL,
    debtor_type_id integer NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone,
    deleted_at timestamp with time zone,
    CONSTRAINT debtor_pkey PRIMARY KEY (debtor_id),
    CONSTRAINT debtor_debtor_type_ukey UNIQUE (case_id, debtor_type_id, person_id)
);

CREATE TABLE IF NOT EXISTS public.genders
(
    gender_id serial NOT NULL,
    name character varying(10) NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone,
    deleted_at timestamp with time zone,
    CONSTRAINT genders_pkey PRIMARY KEY (gender_id)
);

CREATE TABLE IF NOT EXISTS public.partners
(
    partner_id serial NOT NULL,
    name character varying(200) COLLATE pg_catalog."default" NOT NULL,
    sector_id integer NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone,
    deleted_at timestamp with time zone,
    CONSTRAINT partners_pkey PRIMARY KEY (partner_id)
);

CREATE TABLE IF NOT EXISTS public.persons
(
    person_id serial NOT NULL,
    first_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    last_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    birth_place_city_id integer NOT NULL,
    birth_date date NOT NULL,
    birth_name character varying(150) COLLATE pg_catalog."default",
    mother_name character varying(150) COLLATE pg_catalog."default" NOT NULL,
    death_date date,
    gender_id integer NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone,
    deleted_at timestamp with time zone,
    CONSTRAINT persons_pkey PRIMARY KEY (person_id)
);

CREATE TABLE IF NOT EXISTS public.purchases
(
    purchase_id serial NOT NULL,
    partner_id integer NOT NULL,
    batch_number character varying(50) COLLATE pg_catalog."default" NOT NULL,
    purchased_at date NOT NULL,
    batch_purchase_value integer NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone,
    deleted_at timestamp with time zone,
    CONSTRAINT purchases_pkey PRIMARY KEY (purchase_id)
);

CREATE TABLE IF NOT EXISTS public.regions
(
    region_id serial NOT NULL,
    name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone,
    deleted_at timestamp with time zone,
    CONSTRAINT regions_pkey PRIMARY KEY (region_id)
);

CREATE TABLE IF NOT EXISTS public.sectors
(
    sector_id serial NOT NULL,
    name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone,
    deleted_at timestamp with time zone,
    CONSTRAINT sectors_pkey PRIMARY KEY (sector_id)
);

CREATE TABLE IF NOT EXISTS public.test
(
    test_id serial NOT NULL,
    n integer NOT NULL,
    CONSTRAINT test_pkey PRIMARY KEY (test_id)
);

CREATE TABLE IF NOT EXISTS public.bank_accounts
(
    bank_account_id serial NOT NULL,
    account_number character(26) NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone,
    deleted_at timestamp with time zone,
    CONSTRAINT bank_accounts_pkey PRIMARY KEY (bank_account_id)
);

CREATE TABLE IF NOT EXISTS public.account_holders
(
    account_holder_id serial NOT NULL,
    person_id integer NOT NULL,
    bank_account_id integer NOT NULL,
    valid_from date NOT NULL,
    valid_to date,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone,
    deleted_at timestamp with time zone,
    CONSTRAINT account_holders_pkey PRIMARY KEY (account_holder_id),
    CONSTRAINT person_bank_account_ukey UNIQUE (person_id, bank_account_id)
);

CREATE TABLE IF NOT EXISTS public.payments
(
    payment_id serial NOT NULL,
    amount integer NOT NULL,
    payment_date date NOT NULL,
    bank_account_id integer NOT NULL,
    person_id integer NOT NULL,
    case_id integer NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone,
    deleted_at timestamp with time zone,
    CONSTRAINT payments_pkey PRIMARY KEY (payment_id)
);

CREATE TABLE IF NOT EXISTS public.fin_publicated_data
(
    account_number character(26) COLLATE pg_catalog."default" NOT NULL,
    account_valid_from date NOT NULL,
    account_valid_to date,
    bank_account_id integer NOT NULL,
    first_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    last_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    birth_name character varying(150) COLLATE pg_catalog."default",
    person_id integer NOT NULL,
    partner_case_number character varying(100) COLLATE pg_catalog."default" NOT NULL,
    amount numeric(16, 3) NOT NULL,
    balance numeric(16, 3) NOT NULL,
    purchased_at date NOT NULL,
    case_id integer NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT fin_publicated_data_pkey PRIMARY KEY (bank_account_id, person_id, case_id)
);

CREATE TABLE IF NOT EXISTS public.debts
(
    debt_id serial NOT NULL,
    case_id integer NOT NULL,
    calculated_from date NOT NULL,
    calculated_to date NOT NULL,
    debt_amount numeric(16, 3) NOT NULL,
    interest_rate numeric(6, 3) NOT NULL,
    interest_amount numeric(16, 3) NOT NULL,
    open_debt boolean NOT NULL DEFAULT false,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone,
    deleted_at timestamp with time zone,
    CONSTRAINT debts_pkey PRIMARY KEY (debt_id)
);

CREATE TABLE IF NOT EXISTS public.payed_debts
(
    payed_debt_id serial NOT NULL,
    debt_id integer NOT NULL,
    payment_id integer NOT NULL,
    debt_amount_covered numeric(16, 3) NOT NULL,
    interest_amount_covered numeric(16, 3) NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone,
    deleted_at timestamp with time zone,
    CONSTRAINT payed_debts_pkey PRIMARY KEY (payed_debt_id)
);

ALTER TABLE IF EXISTS public.cases
    ADD CONSTRAINT case_purchase_fkey FOREIGN KEY (purchase_id)
    REFERENCES public.purchases (purchase_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS fki_case_purchase_fkey
    ON public.cases(purchase_id);


ALTER TABLE IF EXISTS public.cities
    ADD CONSTRAINT city_region_fkey FOREIGN KEY (region_id)
    REFERENCES public.regions (region_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS fki_city_region_fkey
    ON public.cities(region_id);


ALTER TABLE IF EXISTS public.debtors
    ADD CONSTRAINT debtor_case_fkey FOREIGN KEY (case_id)
    REFERENCES public.cases (case_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS fki_debtor_case_fkey
    ON public.debtors(case_id);


ALTER TABLE IF EXISTS public.debtors
    ADD CONSTRAINT debtor_debtor_type_fkey FOREIGN KEY (debtor_type_id)
    REFERENCES public.debtor_types (debtor_type_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS fki_debtor_debtor_type_fkey
    ON public.debtors(debtor_type_id);


ALTER TABLE IF EXISTS public.debtors
    ADD CONSTRAINT debtor_person_fkey FOREIGN KEY (person_id)
    REFERENCES public.persons (person_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS fki_debtor_person_fkey
    ON public.debtors(person_id);


ALTER TABLE IF EXISTS public.partners
    ADD CONSTRAINT parner_sector_fkey FOREIGN KEY (sector_id)
    REFERENCES public.sectors (sector_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS fki_fk_parner_sector
    ON public.partners(sector_id);


ALTER TABLE IF EXISTS public.persons
    ADD CONSTRAINT person_birth_city_fkey FOREIGN KEY (birth_place_city_id)
    REFERENCES public.cities (city_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS fki_person_birth_city_fkey
    ON public.persons(birth_place_city_id);


ALTER TABLE IF EXISTS public.persons
    ADD CONSTRAINT person_gender_fkey FOREIGN KEY (gender_id)
    REFERENCES public.genders (gender_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS fki_person_gender_fkey
    ON public.persons(gender_id);


ALTER TABLE IF EXISTS public.purchases
    ADD CONSTRAINT purchase_partner_fkey FOREIGN KEY (partner_id)
    REFERENCES public.partners (partner_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS fki_fk_purchase_partner
    ON public.purchases(partner_id);


ALTER TABLE IF EXISTS public.account_holders
    ADD CONSTRAINT person_fkey FOREIGN KEY (person_id)
    REFERENCES public.persons (person_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS fki_person_fkey
    ON public.account_holders(person_id);


ALTER TABLE IF EXISTS public.account_holders
    ADD CONSTRAINT bank_account_fkey FOREIGN KEY (bank_account_id)
    REFERENCES public.bank_accounts (bank_account_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS fki_bank_account_fkey
    ON public.account_holders(bank_account_id);


ALTER TABLE IF EXISTS public.payments
    ADD CONSTRAINT payment_person_fkey FOREIGN KEY (person_id)
    REFERENCES public.persons (person_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS fki_payment_person_fkey
    ON public.payments(person_id);


ALTER TABLE IF EXISTS public.payments
    ADD CONSTRAINT payment_bank_account_fkey FOREIGN KEY (bank_account_id)
    REFERENCES public.bank_accounts (bank_account_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS fki_payment_bank_account_fkey
    ON public.payments(bank_account_id);


ALTER TABLE IF EXISTS public.payments
    ADD CONSTRAINT payment_case_fkey FOREIGN KEY (case_id)
    REFERENCES public.cases (case_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS fki_payment_case_fkey
    ON public.payments(case_id);


ALTER TABLE IF EXISTS public.fin_publicated_data
    ADD CONSTRAINT fin_publicated_data_bank_account_fkey FOREIGN KEY (bank_account_id)
    REFERENCES public.bank_accounts (bank_account_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS fki_fin_publicated_data_bank_account_fkey
    ON public.fin_publicated_data(bank_account_id);


ALTER TABLE IF EXISTS public.fin_publicated_data
    ADD CONSTRAINT fin_publicated_data_person_id_fkey FOREIGN KEY (person_id)
    REFERENCES public.persons (person_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS fki_fin_publicated_data_person_id
    ON public.fin_publicated_data(person_id);


ALTER TABLE IF EXISTS public.fin_publicated_data
    ADD CONSTRAINT fin_publicated_data_case_id FOREIGN KEY (case_id)
    REFERENCES public.cases (case_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS fki_fin_publicated_data_case_id
    ON public.fin_publicated_data(case_id);


ALTER TABLE IF EXISTS public.debts
    ADD CONSTRAINT debt_case_fkey FOREIGN KEY (case_id)
    REFERENCES public.cases (case_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS fki_debt_case_fkey
    ON public.debts(case_id);


ALTER TABLE IF EXISTS public.payed_debts
    ADD CONSTRAINT coverage_debt_fkey FOREIGN KEY (debt_id)
    REFERENCES public.debts (debt_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS fki_debts_fkey
    ON public.payed_debts(debt_id);


ALTER TABLE IF EXISTS public.payed_debts
    ADD CONSTRAINT coverage_payment_fkey FOREIGN KEY (payment_id)
    REFERENCES public.payments (payment_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS fki_payments_fkey
    ON public.payed_debts(payment_id);

END;